### ISSUE TITLE
Servo Control

### ISSUE THREAD

**Issue by AlexanderEhle** [fx-bricks/pfx-brick-dev#10]
The LEGO Servo allows steering of 90 degree right or left with totally 15 Steps/Positions (7 positions on each side an the 0 Degree). I suggest an new Effect to control the Servo more detailed.

6 Positions each with 15 Degree. So, we can offer the Position: 0, 15, 30, 45, 60, 75, 90 Degree.

- Servo left - Position as Parameter (0, +15, +30, +45, +60, +75, +90)
- Servo right - Position as Parameter (0, -15, -30, -45, -60, -75, -90)
- Servo centered (0)
- Change Direction (use current position and go to the opposite, e.g. +30 to -30 degree)

With speed control, you can set the position stepwise with the wheels.

**Comment by AlexanderEhle** [comment]
Two new effect types
- Servo +1 Step (increase position +15 Deg, stops at +90 Degree)
- Servo -1 Step (decrease position -15 Deg, stops at -90 Degree)

**Comment by michaelgale** [comment]
Before developing the PFx Brick, I had not used the Lego servo motor.  When I finally bought one to test its operation, I was quite disappointed that it was not a continuously variable servo but a 15 position discrete position device!   

In any case, I think the solution is simply to add SPEED_STEP parameters labelled for servo motor operation, i.e. +/-15 degrees (rather than +/- %value).  Internally, the PFx Brick will ignore the speed mapping curve and set the output voltage directly as required to set a servo position.

**Comment by AlexanderEhle** [comment]
Yes, thats LEGO. But we must deal with. Adding Parameters labeled with Degrees and set the appropriate DutyCycle to positioning the Servo would be nice.
